name: instagram
version: 1.0.0
description: Dart Instagram client library
homepage: https://github.com/simplenotexy/instagram_dart
environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  oauth2: ^2.0.1
dev_dependencies:
  test: ^1.16.5
